package ripe

import (
	"context"
	"strings"
	"testing"
)

const sample = `# generated by riped
inetnum:        192.0.2.0 - 192.0.2.255
netname:        TEST-NET-1
descr:          Documentation prefix
descr:          second descr
                continued on this line
country:        ZZ
admin-c:        ABC123-RIPE
source:         RIPE

person:         John Doe
address:        1 Test Street
                Test City
                ZZ
nic-hdl:        ABC123-RIPE
source:         RIPE

% just a comment
route:          192.0.2.0/24
origin:         AS65000
source:         RIPE
`

func TestParseBasic(t *testing.T) {
	var got []*Object
	err := parseStream(context.Background(), strings.NewReader(sample), func(o *Object) error {
		got = append(got, o)
		return nil
	})
	if err != nil {
		t.Fatalf("parse: %v", err)
	}
	if len(got) != 3 {
		t.Fatalf("want 3 objects, got %d", len(got))
	}

	in := got[0]
	if in.Class != "inetnum" {
		t.Errorf("class=%q", in.Class)
	}
	if in.PrimaryKey != "192.0.2.0 - 192.0.2.255" {
		t.Errorf("pk=%q", in.PrimaryKey)
	}
	descrs := in.LookupAll("descr")
	if len(descrs) != 2 {
		t.Fatalf("want 2 descr, got %d (%v)", len(descrs), descrs)
	}
	if !strings.Contains(descrs[1], "continued on this line") {
		t.Errorf("continuation not folded: %q", descrs[1])
	}

	p := got[1]
	if p.Class != "person" || p.PrimaryKey != "John Doe" {
		t.Errorf("person parse wrong: %+v", p)
	}
	addr := p.Lookup("address")
	if !strings.Contains(addr, "Test City") || !strings.Contains(addr, "ZZ") {
		t.Errorf("address continuation lost: %q", addr)
	}

	r := got[2]
	if r.Class != "route" || r.PrimaryKey != "192.0.2.0/24" {
		t.Errorf("route parse wrong: %+v", r)
	}
}
